ch-support-multiple-languages
atlp-rwanda/Phantom-frontend-pirates pull request #3
Opened 2022-04-05 14:38 UTC by JPaul23

# Overview
This chore was about to install i18next in our web app. Now we can support multiple languages in Phantom react app.
The supported languages are `english`, `french` and `Kinyarwanda`.
The following images are translations

<img src="https://i.ibb.co/BchRjcH/en.png" alt="en" border="0" />
<img src="https://i.ibb.co/wMy3LHj/fr.png" alt="fr" border="0" />
<img src="https://i.ibb.co/mhfxFG6/rw.png" alt="rw" border="0" />

2022-04-06 09:37 UTC, NyiingangoPacifique approved these changes

2022-04-07 06:00 UTC, SimonImanigirimpuhwe requested changes
Try to complete your setup so that a user can select a preferred language and maintain it in your store

2022-04-07 06:00 UTC, SimonImanigirimpuhwe commented on public/assets/i18n/translations/en.json
> +    "valid_name": "enter valid name",
Why these messages are static while are messages that are supposed to come from the backend?

2022-04-07 06:00 UTC, SimonImanigirimpuhwe commented on public/assets/i18n/translations/en.json
> +    "delete_impossible": "This route is not in database to be deleted",
Since you have multiple languages enabled on the backend, for frontend you only need to add static texts that are not supposed to be backend responses.

2022-04-07 06:00 UTC, SimonImanigirimpuhwe commented on src/App.js
> +            <Route path='/' element = { <LandingPage t = { t } /> } />
Instead of passing `useTranslation` here, you could have imported this component with a hook called `withTranslation` which will allow you to use translations across that component.

2022-04-07 06:00 UTC, SimonImanigirimpuhwe commented on src/container/LandingPage.jsx
>  )}
Your setup is incomplete, there is no way the user can choose the language of preference.
You need to create a reducer and an action for the selected language so that you will be able to maintain the selected language. And also give the user the ability to select a language which will also be sent to your server to trigger responses in a selected language.

2022-04-13 21:46 UTC, JPaul23 commented on public/assets/i18n/translations/en.json
> +    "delete_impossible": "This route is not in database to be deleted",
This was resolved

2022-04-13 21:46 UTC, JPaul23 commented on public/assets/i18n/translations/en.json
> +    "valid_name": "enter valid name",
This was resolved

2022-04-13 21:49 UTC, JPaul23 commented on public/assets/i18n/translations/en.json
> +    "delete_impossible": "This route is not in database to be deleted",
### This is relying on backend and i18n for translations.

<img src="https://i.ibb.co/RvMjHDX/2.png" alt="2" border="0" />

2022-04-19 06:51 UTC, SimonImanigirimpuhwe requested changes

2022-04-19 06:51 UTC, SimonImanigirimpuhwe commented on src/app/store.js
> +import { phantomApi } from '../services/phantomApi';
We can have two stores in one application. 
Please if you decide to go with `redux toolkit` stick to it.

2022-04-19 06:51 UTC, SimonImanigirimpuhwe commented on src/container/LandingPage.jsx
> +    }, [language])
Remove this useless code

2022-04-19 06:51 UTC, SimonImanigirimpuhwe commented on src/services/phantomApi.js
> +const baseUrl = 'https://phantom-api-pirates.herokuapp.com/';
Make this an environment variable so that it can't be seen directly in the codebase

2022-04-26 11:54 UTC, JPaul23 commented
There is a bug in rendering **SearchBox component** and **Login component**

2022-04-28 09:18 UTC, closed without merging